
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
builder.Services.AddSyncfusionBlazor();
SyncfusionLicenseProvider.RegisterLicense("NTM1MTg3QDMxMzkyZTMzMmUzMG8zbU5GRmtEYmpGN2lKaVYyRU53VUx2ei9XUXlSTjJoM2NuZit5cmJjMDg9;NTM1MTg4QDMxMzkyZTMzMmUzMFdmamc4N05JbkNyb3dncnhEVnZuTVJvNVpRazVLUGdIbHNUM1UwdzFERHc9;NTM1MTg5QDMxMzkyZTMzMmUzMEFZYUhsQXNCQkZVU2FuOCtaZmc3aGN1dGlvMUp3d1h0Z1R2VVlmcXRzREk9;NTM1MTkwQDMxMzkyZTMzMmUzMERzVTRoaGRueFVQdjNFYzFqUi9ldnU4ZnVRL2w0WFU5UitDcEVJWHZvMjA9;NTM1MTkxQDMxMzkyZTMzMmUzMGE5MFVEMmNjZHBoNUpZTkRLU2VEL1ZkZE5UMThzS2M5N081NkRCQ2J4azg9;NTM1MTkyQDMxMzkyZTMzMmUzMGtVYkVHdzhKQVoxQVlOM3JZemhSK3p6RTEvdG9pWkxTRVFST013NnNzNmM9;NTM1MTkzQDMxMzkyZTMzMmUzMExyU1FVOFNkUGw3dXRqS05Kc1ZqUUpHMUtFRFU5bTZrRHl3eDk5b3Nyb2c9;NTM1MTk0QDMxMzkyZTMzMmUzMFlPWEprV2RhdWhTSnl2SkdkaC9yd1hqN2tlOUZMMGx2NUFxNkFvOVRraGs9;NTM1MTk1QDMxMzkyZTMzMmUzMG1PNUNQbFYrQU5wQ1lkQmpZWUpSUm8zNndLdkRFYmxlc0NxNVVBVmM5TUk9;NTM1MTk2QDMxMzkyZTMzMmUzMEltQnpGZnkzUzd6YzRIaWxvWHdjQUVXcldTNkdaN1pWV2xRa2laMGhlb1k9;NTM1MTk3QDMxMzkyZTMzMmUzMENZZXpzVCtlMHlQUUM1dnY0VVlDcURmN015MUd0clhDL3hQcWhveGVoK0E9");
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddScoped<ICountryRepository, CountryRepository>();
builder.Services.AddScoped<IHttpService, HttpService>();
await builder.Build().RunAsync();
